kind: Job
apiVersion: batch/v1
metadata:
  name: job
  namespace: nginxsaroj
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: demo-job-po
      labels:
        app: batch-task
    spec:
      containers:
        - name: batch-container
          image: busybox:latest
          command: ["sh", "-c", "echo Hello Anurag && sleep 10" ]
      restartPolicy: Never
