apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
  namespace: nginxsaroj
  labels:
    app: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
