apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvs
  namespace: nginxsaroj
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

